
data=[-0.001,0.25,0.61,1+eps(2)]';
num_edges=6;
min_edge=0;
max_edge=1;
edges=linspace(min_edge,max_edge,num_edges)';
[out1,out1_edges]=even_spaced_hist(data,0,1,num_edges);
out1
out2=histcounts(data,[-inf;edges;inf])'
[out3,out3_edges]=histcounts(data,num_edges-1,'BinLimits',[min_edge,max_edge]);
out3=out3';
isequal(out1,out2)
isequal(out2(2:end-1),out3)
isequal(out1(2:end-1),out3)
%are the edges generated by histcounts within tolerance of linspace
sum(abs(out3_edges'-edges)>eps*10)==0


%%
fprintf('INFO:running test of 3 methods\n')
data=rand(1e7,1)-0.1;
num_edges=500;
min_edge=0;
max_edge=1;

logic_str={'FAIL','pass'};
runtime_my_even_hist=tic;
[out1,out1_edges]=even_spaced_hist(data,0,1,num_edges);
runtime_my_even_hist=toc(runtime_my_even_hist);

runtime_histcounts_linspace=tic;
edges=linspace(min_edge,max_edge,num_edges)';
out2=histcounts(data,[-inf;edges;inf])';
runtime_histcounts_linspace=toc(runtime_histcounts_linspace);

runtime_histcounts_even=tic;
[out3,out3_edges]=histcounts(data,num_edges-1,'BinLimits',[min_edge,max_edge]);
runtime_histcounts_even=toc(runtime_histcounts_even);

fprintf('INFO:RUNTIME my even spaced hist     : %f\n',runtime_my_even_hist)
fprintf('INFO:RUNTIME my even spaced hist mex : %f\n',runtime_my_even_mex_hist)
fprintf('INFO:RUNTIME histcounts(linspace)    : %f\n',runtime_histcounts_linspace)
fprintf('INFO:RUNTIME histcounts(even)        : %f\n',runtime_histcounts_even)

out3=out3';
fprintf('TEST: outputs equal my even spaced hist, histcounts(linspace)     : %s\n',logic_str{1+isequal(out1,out2)})
fprintf('TEST: outputs equal histcounts(linspace), histcounts(even)        : %s\n',logic_str{1+isequal(out2(2:end-1),out3)})
fprintf('TEST: outputs equal my even spaced hist, histcounts(even)         : %s\n',logic_str{1+isequal(out1(2:end-1),out3)})
fprintf('TEST: edges equal(±eps) my even spaced hist, histcounts(even)     : %s\n',logic_str{1+(sum(abs(out3_edges'-edges)>eps*2)==0)})
%interesting my algo spits out exaxtly the same edges except for the last edge
%are the edges generated by histcounts within tolerance of linspace
figure(1)
set(gca,'color','w')
plot(out1(2:end-1))
hold on
plot(out2(2:end-1))
plot(out3)
hold off


